name: async_forms
description: Rewrited flutter_forms package with async validation and more
version: 0.0.2
repository: https://github.com/odrya12/flutter_async_forms

environment:
  sdk: ">=3.0.1 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
